### ISSUE TITLE
Update for Webpack 4 

### ISSUE THREAD

**Issue by ghost** [alexblunck/html-webpack-plugin-remove#2]
Can you update?
<img width="587" alt="screen shot 2018-03-08 at 14 19 10" src="https://user-images.githubusercontent.com/1254613/37148508-b9068ad2-22db-11e8-8dbe-5d1fa35e735a.png">

**Comment by alexblunck** [comment]
Hi, I just published version `0.1.0` which supports webpack 4

**Comment by ghost** [comment]
Thanks for quick response. What am i missing in this regex?
`new HtmlPluginRemove(/<!--deletestart-->(.*)<!--deleteend-->/),`

**Comment by ghost** [comment]
For Javascript, i found the correct match. Thanks again. 
`[\s\S]*`
